# Common settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
server.tomcat.threads.max=4
spring.servlet.multipart.max-file-size=32MB
spring.servlet.multipart.max-request-size=32MB
spring.web.resources.static-locations[0]=file:src/main/resources/webapp/
spring.web.resources.static-locations[1]=classpath:/webapp/

# Use environment variables for secrets
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
eisenhower.jwt.signingkey=${JWT_SIGNING_KEY}